### ISSUE TITLE
Bug in MAC address list after WiFi scanning, replace `r.mac_address[4]` with `r.mac_address[5]` in `cli-cmd-wifi.c` file

### ISSUE THREAD

**Issue by ZenoMaverick** [Abeeway/abeeway-geolocation-module#10]
### Description
I noticed a small bug when trying the Wi-Fi scanning function on the 1WL EVK with the app-cmty-demo firmware.
**When the MAC address results are displayed, the first and second byte seem to be duplicated**.
I checked against a Wi-Fi analyzer and confirmed the MAC address is incorrect.
Bug seen in both abw and cmty demo versions.

### Screenshots
![image](https://user-images.githubusercontent.com/75191765/221081520-bf243318-66dc-4978-886d-81ecffbc7105.png)
![WiFi_Analyzer](https://user-images.githubusercontent.com/75191765/221080960-ea78dc5a-5fd2-40e3-8637-36e7909a6e47.png)

**Comment by ZenoMaverick** [comment]
### Issue
![image](https://user-images.githubusercontent.com/75191765/221086558-308bc1bc-c6a9-4d7c-bead-da339fd93001.png)

In _**cli-cmd-wifi.c**_, there's a typo in print statement (line 128, line 180). Simple fix just by changing it to print **r.mac_address[5]** instead of **r.mac_address[4]**.

### Need to replace with this
`cli_printf(" MAC Address: 0x%02x 0x%02x 0x%02x 0x%02x 0x%02x 0x%02x, RSSI: %d\n",
	r.mac_address[0], r.mac_address[1],r.mac_address[2],
	r.mac_address[3], r.mac_address[4], r.mac_address[5], r.rssi);`

### Result
![image](https://user-images.githubusercontent.com/75191765/221088144-39ece438-8c33-4231-8259-921c8f8fb472.png)

**Comment by norbertherbert** [comment]
fixed in v1.1-0
