### ISSUE TITLE
Unexpected reboot by device when opening BLE driver. Using CLI demo

### ISSUE THREAD

**Issue by ZenoMaverick** [Abeeway/abeeway-geolocation-module#13]
### Description
Seeing a bug where device reboots when trying to open BLE driver. Can anyone verify on their side?
This was tested with CLI demo and using version 2022.11.29.

### Screenshots
![1WL_Reboot_BLE](https://user-images.githubusercontent.com/75191765/235633079-3029c3e8-3b21-4f05-bfaf-8b2b03cf8724.png)

**Comment by ZenoMaverick** [comment]
Hi @norbertherbert I have a EVB v2.3, could I check if there are any issues to use this v2.3 kit with the latest SDK and the demo files? Thanks!

**Comment by norbertherbert** [comment]
Please try the new AOS SDK v1.1-0
