### ISSUE TITLE
Please correct README and LEDs used for toggling and downlink msg to avoid confusion

### ISSUE THREAD

**Issue by ZenoMaverick** [Abeeway/abeeway-geolocation-module#14]
## Description

- There are some discrepancies that should be corrected to avoid confusion for new users after flashing first demo.

- Is LED3 or LED4 suppose to be blinking? Which LED is suppose to toggle state based on the downlink message received?
 
- Four demo applications were attached in this SDK and they have some inconsistencies between them which should be corrected especially for new users.
 

## Screenshots
**README initially mentions LED4 blinking originally.**
> A simple demo application running as an RTOS task with the following features:
Blinking LED_4 of the board

**README then says then says LED3 blinking instead. Please correct this.**
> Check if LED_3 is blinking with 1000ms prdiod

**In main.c of some demos, line 125 should be edited to LED4 instead of LED3 to avoid confusion**
![image](https://user-images.githubusercontent.com/75191765/235667147-7ad521f5-0f92-4f4d-94bb-fa2ea43e0c92.png)

More confusion when running the CLI demo where LED4 is toggling during the demo application but it is also supposed to turn off/on when downlink is received.

![image](https://user-images.githubusercontent.com/75191765/235669413-d5da7ac7-3b10-4ce0-affa-c29bdb1f2a2b.png)

![image](https://user-images.githubusercontent.com/75191765/235669214-c9c27415-244c-4439-b83e-03befa3c8666.png)

I initially thought the downlink messages were not received properly or the LED had some issues until I looked into the source code. Please consider changing this for customers evaluation in next commit. Thanks!

**Comment by norbertherbert** [comment]
not relevant for v1.1-0
