### ISSUE TITLE
Update AN_Geoloc-Module_first-flash.docx

### ISSUE THREAD

**Issue by rohitgecActility** [Abeeway/abeeway-geolocation-module#22]
Hi Norbert,

WE need to update the first flash document. See email from Stephane below.
 

Note I have updated the

Icône docx[ AN_Geoloc-Module_first-flash.docx](https://actilitysa.sharepoint.com/:w:/t/aby/EfG17nLzkEBDuWR47HNiuWMBLQZ8ewmNdPtSHyqsyS9gwA?e=5KZ3FT)

With a section on the watchdog which needs to be configured correctly once you load the mfg or when set-up the EVK for the first time (section3.2)

Maybe Norbert you can update doc in docs/Type1WL-EVB_first_flash.md

**Comment by norbertherbert** [comment]
Done

**Comment by norbertherbert** [comment]
Done
